services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "55001:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    command: ["flask", "run", "--host=0.0.0.0"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
